FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py --break-system-packages
RUN pip install --no-cache-dir pytest --break-system-packages

# Allow jenkins user to access docker socket
RUN usermod -aG docker jenkins

USER jenkins

